CREATE TABLE IF NOT EXISTS `project-6e19992f-9af5-4761-8e9.bq_slv_bein.subscription_cumulated` (
  opco_code STRING NOT NULL,
  subscription_key STRING NOT NULL,
  subscriber_id STRING NOT NULL,
  subscription_name STRING,
  subscription_id STRING,
  activity_array ARRAY<INT64>,
  viewer_array ARRAY<INT64>,
  mou_array ARRAY<FLOAT64>,
  first_active_date DATE,
  last_active_date DATE,
  paid_through_date DATE,
  churn_date DATE,
  last_churn_date DATE,
  last_winback_date DATE,
  is_paying INT64,
  is_in_grace INT64,
  is_active_subscription INT64,
  is_churned INT64,
  is_in_winback_window INT64,
  is_addition INT64,
  is_new_subscription INT64,
  is_winback_event INT64,
  is_reacquisition_event INT64,
  is_churn_event INT64,
  is_renewal_event INT64,
  days_since_last_active INT64,
  days_since_churn INT64,
  tenure_days INT64,
  is_viewer_1d INT64,
  is_viewer_7d INT64,
  is_viewer_30d INT64,
  is_viewer_90d INT64,
  active_days_7d INT64,
  active_days_30d INT64,
  active_days_90d INT64,
  mou_1d FLOAT64,
  mou_7d FLOAT64,
  mou_30d FLOAT64,
  mou_90d FLOAT64,
  snapshot_date DATE NOT NULL
)
PARTITION BY snapshot_date
CLUSTER BY opco_code, subscription_key
OPTIONS (require_partition_filter = TRUE);
